/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank.management.system;

import java.awt.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.spi.DirStateFactory.Result;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import net.proteanit.sql.*;

/**
 *
 * @author mohamed
 */
public class Home_Manager_Access extends javax.swing.JFrame {

    Connection con;
    Statement st = null, st2 = null;
    ResultSet rs = null, rs2 = null;
    

    /**
     * Creates new form Home_Manager_Access
     */
    
    
    public Home_Manager_Access() {
     
        initComponents();
        Set_Max_size();
        conectDB();
        show_Employee_On_Table();
        Employee_phone_no_text.setText("20");
        Edit_Button.setVisible(false);
        emcount();

    }

    public void Set_Max_size() {
        this.setResizable(false);
        this.setAlwaysOnTop(true);
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize = scnMax.bottom;
        this.setSize(xsize, ysize - taskBarSize);
    }

    public void conectDB() {
        try {                            //;create=true
            String url = "jdbc:derby://localhost:1527/bankmangement";
            String user = "user1";
            String password = "1234";
            con = DriverManager.getConnection(url, user, password);
            st = con.createStatement();
            String SQL = "SELECT id,name,birthdate,gender,address,phonenumber,email,salary FROM EMPLOYEE ";
            rs = st.executeQuery(SQL);

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }

    public void show_Employee_On_Table() {
        try {
            st = con.createStatement();
            rs = st.executeQuery("SELECT id,name,birthdate,gender,address,phonenumber,email,salary FROM EMPLOYEE ");
            Employee_Table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Employee_salary_text = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Employee_phone_no_text = new javax.swing.JTextField();
        Employee_address_text = new javax.swing.JTextField();
        Employee_Email = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Employee_Name_text = new javax.swing.JTextField();
        Employee_email_text = new javax.swing.JTextField();
        Employee_Gender_text = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Employee_Table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        Add_Button = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Employee_date_birth_text = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Employee_password_text = new javax.swing.JPasswordField();
        Reset_Button = new javax.swing.JButton();
        Edit_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1550, 860));

        jPanel2.setBackground(new java.awt.Color(34, 153, 113));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jButton1.setText("Add Employee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jButton2.setText("Show Employees Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jButton3.setText("Show Employees Number");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jButton4.setText("Remove Employee");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/logout.png"))); // NOI18N
        jLabel12.setText("logout");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/bank-icon-Manager_Home.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 70)); // NOI18N
        jLabel2.setText("Add Employee");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel3.setText("Gender");

        Employee_salary_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_salary_textActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel5.setText("Date of Birth");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel4.setText("Address");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel7.setText("Name");

        Employee_phone_no_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_phone_no_textActionPerformed(evt);
            }
        });

        Employee_address_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_address_textActionPerformed(evt);
            }
        });

        Employee_Email.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        Employee_Email.setText("E-Mail");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel8.setText("Salary");

        Employee_Name_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_Name_textActionPerformed(evt);
            }
        });

        Employee_email_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_email_textActionPerformed(evt);
            }
        });

        Employee_Gender_text.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        Employee_Gender_text.setPreferredSize(new java.awt.Dimension(6, 22));
        Employee_Gender_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_Gender_textActionPerformed(evt);
            }
        });

        Employee_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Date of Birth", "Phone Number", "Gender", "Adress", "E-Mail", "Salary"
            }
        ));
        Employee_Table.setGridColor(new java.awt.Color(34, 153, 113));
        Employee_Table.setRowHeight(25);
        Employee_Table.setSelectionBackground(new java.awt.Color(34, 153, 113));
        Employee_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Employee_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Employee_Table);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel9.setText("List of Employees");

        Add_Button.setBackground(new java.awt.Color(34, 153, 113));
        Add_Button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Add_Button.setText("ADD");
        Add_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_ButtonMouseClicked(evt);
            }
        });
        Add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_ButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel10.setText("Phone Number");

        Employee_date_birth_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_date_birth_textActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel11.setText("Password");

        Reset_Button.setBackground(new java.awt.Color(34, 153, 113));
        Reset_Button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Reset_Button.setText("Reset");
        Reset_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_ButtonActionPerformed(evt);
            }
        });

        Edit_Button.setBackground(new java.awt.Color(34, 153, 113));
        Edit_Button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Edit_Button.setLabel("Edit");
        Edit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Employee_salary_text)
                            .addComponent(Employee_Name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Employee_phone_no_text, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Employee_date_birth_text, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(Employee_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(17, 17, 17)))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Employee_password_text)
                            .addComponent(Employee_email_text)
                            .addComponent(Employee_Gender_text, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Employee_address_text, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Reset_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Edit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(364, 364, 364)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(98, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Employee_Name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Employee_address_text, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Employee_Gender_text, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Employee_phone_no_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Employee_email_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Employee_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Employee_date_birth_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Employee_salary_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Employee_password_text, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_Button)
                    .addComponent(Reset_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        Edit_Button.getAccessibleContext().setAccessibleName("Edite");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1774, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        Manager_login Manager_login = new Manager_login();
        Manager_login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Home_Manager_Acess_2 Remove_Employee = new Home_Manager_Acess_2();
        Remove_Employee.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed
    int number_of_Employees = 0;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            st = con.createStatement();
            String Query = "select count(*) from Employee ";
            rs = st.executeQuery(Query);
            rs.next();
            int count = rs.getInt(1);
            JOptionPane.showMessageDialog(this, "Number of Employees is " + count);
        } catch (SQLException ex) {
            Logger.getLogger(Home_Manager_Access.class.getName()).log(Level.SEVERE, null, ex);
        }
  

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Home_Manager_Access_3 Show_Data = new Home_Manager_Access_3();
        Show_Data.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Employee_salary_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_salary_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Employee_salary_textActionPerformed

    private void Employee_date_birth_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_date_birth_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Employee_date_birth_textActionPerformed

    private void Employee_phone_no_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_phone_no_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Employee_phone_no_textActionPerformed

    private void Employee_Name_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_Name_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Employee_Name_textActionPerformed

    private void Employee_email_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_email_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Employee_email_textActionPerformed

    private void Employee_Gender_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_Gender_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Employee_Gender_textActionPerformed

    private void Employee_address_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_address_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Employee_address_textActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        Manager_login Manager_login = new Manager_login();
        Manager_login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void Reset_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_ButtonActionPerformed
        Employee_Name_text.setText("");
        Employee_phone_no_text.setText("");
        Employee_date_birth_text.setText("");
        Employee_salary_text.setText("");
        Employee_address_text.setText("");
        Employee_email_text.setText("");
        Employee_password_text.setText("");
        Add_Button.setVisible(true);
        Edit_Button.setVisible(false);
        Employee_Name_text.setEnabled(true);
        Employee_password_text.setEnabled(true);
        Employee_Gender_text.setEnabled(true);
        Employee_date_birth_text.setEnabled(true);
//               this.setVisible(false);
//                this.setVisible(true);

    }//GEN-LAST:event_Reset_ButtonActionPerformed


    private void Add_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_ButtonMouseClicked
        /* if(Employee_Name_text.getText().isEmpty() || Employee_salary_text.getText().isEmpty() ||
           Employee_phone_no_text.getText().isEmpty() || Employee_address_text.getText().isEmpty() ||
           Employee_date_birth_text.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"plz");
            
        }else{
           try{
               int frist_id = 25149896; 
               con = DriverManager.getConnection("jdbc:derby://localhost:1527/BankManagementSystem","Bank","1234");
               st = con.createStatement();
               String SQL = "SELECT * FROM EMPLOYEES ";
               rs = st.executeQuery(SQL);
               PreparedStatement add = con.prepareStatement("insert into EmployeeTbl values(?,?,?,?,?,?,?,?)");
               add.setInt(1,frist_id);
               add.setString(2,Employee_Name_text.getText());
               add.setString(3,Employee_date_birth_text.getText());
               add.setString(4,Employee_phone_no_text.getText());
               add.setString(5,Employee_Gender_text.getSelectedItem().toString());
               add.setString(6,Employee_address_text.getText());
               add.setString(7,Employee_email_text.getText());
               add.setString(8,Employee_salary_text.getText());
               int row = add.executeUpdate();
               JOptionPane.showMessageDialog(this,"Employee Added Successfully");
               con.close();
               
           }catch(SQLException ex){
               ex.addSuppressed(ex);
               System.out.println("Error");
           }
            
        }*/

    }//GEN-LAST:event_Add_ButtonMouseClicked

    private void Add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_ButtonActionPerformed
        if (Employee_Name_text.getText().isEmpty() || Employee_salary_text.getText().isEmpty()
                || Employee_phone_no_text.getText().isEmpty() || Employee_address_text.getText().isEmpty()
                || Employee_date_birth_text.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter all Data");

        } else {
            try {
                //number_of_Employees++;
                emcount();
                PreparedStatement add = con.prepareStatement("insert into Employee values(?,?,?,?,?,?,?,?,?)");
                try {
                    add.setInt(1, em_id);
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test1");
                }
//                System.out.println("id in add = " + em_id);
                try {
                    add.setString(2, Employee_Name_text.getText());
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test2");
                }

                try {

                    add.setString(9, Employee_date_birth_text.getText());
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test3");
                }
                try {
                    int phoneno = Integer.parseInt(Employee_phone_no_text.getText());
                    add.setInt(3, phoneno);
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test4");
                }
                try {
                    add.setString(4, Employee_Gender_text.getSelectedItem().toString());
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test5");
                }

                try {
                    add.setString(5, Employee_address_text.getText());
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test6");
                }
                try {
                    add.setString(6, Employee_email_text.getText());
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test7");
                }
                try {
                    double salary = Double.parseDouble(Employee_salary_text.getText());
                    add.setDouble(7, salary);
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test8");
                }
                try {
                    int password = Integer.parseInt(Employee_password_text.getText());
                    add.setInt(8, password);
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test9");
                }
                int row = add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Employee Added Successfully with id : " + em_id );
                show_Employee_On_Table();

                con.close();
//                conectDB();

            } catch (Exception ex) {
                ex.addSuppressed(ex);
                System.out.println("add  Error");
            }

        }

        

    }//GEN-LAST:event_Add_ButtonActionPerformed

//   static int new_id = 1;
//   private int  id_count(){
//       
//        try{
//            
//            st1 = con.createStatement();
//            rs1 = st1.executeQuery("select Max(ID) form User1.employee");
//            rs1.next();
//            
//            new_id = rs1.getInt(1);
//            new_id = new_id + 1;
//           
//        
//              
//        }catch(Exception ex){
//           // System.out.println(ex.getMessage());
//            System.out.println("id error");
//        }
//              
//       
//           return  new_id;   
//    }
    int em_id = 0;

    private void emcount() {

        try {
            st2 = con.createStatement();
            rs2 = st2.executeQuery("select Max(id) from user1.employee");
            rs2.next();
            em_id = rs2.getInt(1) + 1;

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }

    int Employee_id = 0;

    private void Employee_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employee_TableMouseClicked
        DefaultTableModel model = (DefaultTableModel) Employee_Table.getModel();
        int Myindex = Employee_Table.getSelectedRow();
        
        Employee_id = Integer.valueOf(model.getValueAt(Myindex, 0) + "");
        Employee_Name_text.setText(model.getValueAt(Myindex, 1) + "");
        Employee_date_birth_text.setText(model.getValueAt(Myindex, 2) + "");
        Employee_phone_no_text.setText(model.getValueAt(Myindex, 5) + "");
        Employee_email_text.setText(model.getValueAt(Myindex, 6) + "");
        Employee_Gender_text.setSelectedItem(model.getValueAt(Myindex, 3) + "");
        Employee_address_text.setText(model.getValueAt(Myindex, 4) + "");
        Employee_salary_text.setText(model.getValueAt(Myindex, 7) + "");
        Add_Button.setVisible(false);
        Edit_Button.setVisible(true);
        Employee_Name_text.setEnabled(false);
        Employee_password_text.setEnabled(false);
        Employee_Gender_text.setEnabled(false);
        Employee_date_birth_text.setEnabled(false);


    }//GEN-LAST:event_Employee_TableMouseClicked

    private void Edit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_ButtonActionPerformed

        try {

            // name =  ' ahamed ' 
            int phoneno = Integer.parseInt(Employee_phone_no_text.getText());
            double salary = Double.parseDouble(Employee_salary_text.getText());
            
            String q = " update User1.employee set email = '" + Employee_email_text.getText() + "', address = '" + Employee_address_text.getText() + "' ,salary = " + salary + " ,phonenumber = " + phoneno + " where id = " + Employee_id;
            Statement Edit = con.createStatement();
            Edit.executeUpdate(q);
            JOptionPane.showMessageDialog(this, "Employee Edit Successfully");
            show_Employee_On_Table();

        } catch (SQLException ex) {
            Logger.getLogger(Home_Manager_Access.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error in edit");
        }

    }//GEN-LAST:event_Edit_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Manager_Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Manager_Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Manager_Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Manager_Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Manager_Access().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Button;
    private javax.swing.JButton Edit_Button;
    private javax.swing.JLabel Employee_Email;
    private javax.swing.JComboBox<String> Employee_Gender_text;
    private javax.swing.JTextField Employee_Name_text;
    private javax.swing.JTable Employee_Table;
    private javax.swing.JTextField Employee_address_text;
    private javax.swing.JTextField Employee_date_birth_text;
    private javax.swing.JTextField Employee_email_text;
    private javax.swing.JPasswordField Employee_password_text;
    private javax.swing.JTextField Employee_phone_no_text;
    private javax.swing.JTextField Employee_salary_text;
    private javax.swing.JButton Reset_Button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
