/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank.management.system;


import java.awt.Insets;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author mohamed
 */
public class Home_Employee_Create_Account extends javax.swing.JFrame {
   
    
    Connection con;
    Statement st = null ,st2 = null;
    ResultSet rs = null,rs2 = null;
    
    /**
     * Creates new form Home_Employee
     */
    public Home_Employee_Create_Account() {
        initComponents();
        conectDB();
        show_customer_On_Table();
        Set_Max_size();
        S_N_count();
        Edit_Button2.setVisible(false);

        
    }
    
    public void Set_Max_size() {
        this.setResizable(false);
        this.setAlwaysOnTop(true);
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize = scnMax.bottom;
        this.setSize(xsize, ysize - taskBarSize);
    }
    
     public void conectDB() {
        try {                         
            
            String url = "jdbc:derby://localhost:1527/bankmangement";
            String user = "user1";
            String password = "1234";
            con = DriverManager.getConnection(url, user, password);
            st = con.createStatement();
            String SQL = "SELECT serialnumber,name,birthdate,gender,address,phonenumber,email,balance FROM customer ";
            rs = st.executeQuery(SQL);
           
         
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Customer_Balance_text = new javax.swing.JTextField();
        Customer_birth_date_text = new javax.swing.JTextField();
        Customer_phone_no_text = new javax.swing.JTextField();
        Customer_Name_text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Employee_Email = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Customer_password_text = new javax.swing.JPasswordField();
        Customer_Email_text = new javax.swing.JTextField();
        Customer_Gender_text = new javax.swing.JComboBox<>();
        Customer_address_text = new javax.swing.JTextField();
        Reset_Button2 = new javax.swing.JButton();
        Create_Button1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Customer_Table = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        Edit_Button2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1655, 907));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(34, 153, 113));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jButton1.setText("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        jButton2.setText(" Account transaction");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jButton3.setText("Show All Accounts");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jButton4.setText("Delete Account");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/logout.png"))); // NOI18N
        jLabel13.setText("logout");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 84, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel10.setText("List Of Account");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 70)); // NOI18N
        jLabel3.setText("Create Account");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel7.setText("Name");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel11.setText("Phone Number");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel5.setText("Date of Birth");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel8.setText("Balance");

        Customer_Balance_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_Balance_textActionPerformed(evt);
            }
        });

        Customer_birth_date_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_birth_date_textActionPerformed(evt);
            }
        });

        Customer_phone_no_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_phone_no_textActionPerformed(evt);
            }
        });

        Customer_Name_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_Name_textActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel4.setText("Address");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel6.setText("Gender");

        Employee_Email.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        Employee_Email.setText("E-Mail");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel12.setText("Password");

        Customer_Email_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_Email_textActionPerformed(evt);
            }
        });

        Customer_Gender_text.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        Customer_Gender_text.setPreferredSize(new java.awt.Dimension(6, 22));
        Customer_Gender_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_Gender_textActionPerformed(evt);
            }
        });

        Customer_address_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_address_textActionPerformed(evt);
            }
        });

        Reset_Button2.setBackground(new java.awt.Color(34, 153, 113));
        Reset_Button2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Reset_Button2.setText("Reset");
        Reset_Button2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Reset_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_Button2ActionPerformed(evt);
            }
        });

        Create_Button1.setBackground(new java.awt.Color(34, 153, 113));
        Create_Button1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Create_Button1.setText("Create");
        Create_Button1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Create_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_Button1ActionPerformed(evt);
            }
        });

        Customer_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Serial Number", "Name", "Date of Birth", "Phone Number", "Gender", "Adress", "E-Mail", "Salary"
            }
        ));
        Customer_Table.setRowHeight(25);
        Customer_Table.setSelectionBackground(new java.awt.Color(34, 153, 113));
        Customer_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Customer_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Customer_Table);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/bank-icon-Manager_Home.png"))); // NOI18N

        Edit_Button2.setBackground(new java.awt.Color(34, 153, 113));
        Edit_Button2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Edit_Button2.setText("Edit");
        Edit_Button2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Edit_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_Button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Customer_Balance_text)
                                            .addComponent(Customer_Name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Customer_phone_no_text, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Customer_birth_date_text, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(131, 131, 131)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(Employee_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(44, 44, 44))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel6))
                                                .addGap(75, 75, 75)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Customer_Gender_text, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Customer_password_text, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Customer_Email_text, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Customer_address_text, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1072, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(425, 425, 425)
                                        .addComponent(Reset_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Create_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Edit_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(350, 350, 350)
                                .addComponent(jLabel3)))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Customer_Name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Customer_address_text, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Customer_Gender_text, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Customer_phone_no_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Customer_Email_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Employee_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Customer_birth_date_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Customer_Balance_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Customer_password_text, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reset_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Create_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(130, 130, 130))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Employee_Transactions_Access Employee_Transactions_Access = new Employee_Transactions_Access();
      Employee_Transactions_Access.setVisible(true);
      this.setVisible(false);
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Employee_show_Data_Account Employee_show_Data_Account = new Employee_show_Data_Account();
        Employee_show_Data_Account.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       Employee_Delete_Account Home_Employee_Delete = new Employee_Delete_Account();
       Home_Employee_Delete.setVisible(true);
       this.setVisible(false);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Customer_Balance_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_Balance_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_Balance_textActionPerformed

    private void Customer_birth_date_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_birth_date_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_birth_date_textActionPerformed

    private void Customer_phone_no_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_phone_no_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_phone_no_textActionPerformed

    private void Customer_Name_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_Name_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_Name_textActionPerformed

    private void Customer_Email_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_Email_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_Email_textActionPerformed

    private void Customer_Gender_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_Gender_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_Gender_textActionPerformed

    private void Customer_address_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_address_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_address_textActionPerformed

    private void Reset_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_Button2ActionPerformed
        Customer_Name_text.setText("");
        Customer_phone_no_text.setText("");
        Customer_birth_date_text.setText("");
        Customer_Balance_text.setText("");
        Customer_address_text.setText("");
        Customer_Email_text.setText("");
        Customer_password_text.setText("");
        Create_Button1.setVisible(true);
        Edit_Button2.setVisible(false);
        Customer_Name_text.setEnabled(true);
        Customer_password_text.setEnabled(true);
        Customer_Gender_text.setEnabled(true);
        Customer_birth_date_text.setEnabled(true);
        

    }//GEN-LAST:event_Reset_Button2ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        Employee_login  Employee_login = new Employee_login();
        Employee_login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void Create_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_Button1ActionPerformed
        if (Customer_Name_text.getText().isEmpty() || Customer_Balance_text.getText().isEmpty()
                || Customer_phone_no_text.getText().isEmpty() || Customer_address_text.getText().isEmpty()
                ||  Customer_birth_date_text.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter all Data");

        } else {
            try {
              //  serial_number_count();
              S_N_count();
                PreparedStatement add = con.prepareStatement("insert into customer values(?,?,?,?,?,?,?,?,?)");
                try {
                    add.setInt(1,new_s_n);
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test1");
                }
                try {
                    add.setString(2, Customer_Name_text.getText());
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test2");
                }

                try {
                  
                    add.setString(9, Customer_birth_date_text.getText());
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test3");
                }
                try {
                    int phoneno = Integer.parseInt(Customer_phone_no_text.getText());
                    add.setInt(3, phoneno);
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test4");
                }
                try {
                    add.setString(4, Customer_Gender_text.getSelectedItem().toString());
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test5");
                }

                try {
                    add.setString(5, Customer_address_text.getText());
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test6");
                }
                try {
                    add.setString(6, Customer_Email_text.getText());
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test7");
                }
                try {
                    
                    double balance = Double.parseDouble(Customer_Balance_text.getText());
                    if (balance<1000){
                    JOptionPane.showMessageDialog(this, "Please enter balance that greater than or equal 1000");
                    }
                    else
                    add.setDouble(7, balance );
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test8");
                }
                try {
                    int password = Integer.parseInt(Customer_password_text.getText());
                    add.setInt(8, password);
                } catch (Exception ex) {
                    //ex.addSuppressed(ex);
                    System.out.println("test9");
                }
                int row = add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Customer Added Successfully with id: "+new_s_n);
                show_customer_On_Table();

                con.close();
                conectDB();
                

            } catch (Exception ex) {
                //ex.addSuppressed(ex);
                System.out.println("add  Error Customer ");
            }

        }
    }//GEN-LAST:event_Create_Button1ActionPerformed
int Customer_serial_number = 0; 
    private void Customer_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Customer_TableMouseClicked
       
        DefaultTableModel model = (DefaultTableModel) Customer_Table.getModel();
        int Myindex = Customer_Table.getSelectedRow(); 
        Customer_serial_number = Integer.valueOf(model.getValueAt(Myindex,0)+"");
        Customer_Name_text.setText(model.getValueAt(Myindex, 1) + "");
        Customer_birth_date_text.setText(model.getValueAt(Myindex, 2) + "");
        Customer_phone_no_text.setText(model.getValueAt(Myindex, 5) + "");
        Customer_Email_text.setText(model.getValueAt(Myindex, 6) + "");
        Customer_Gender_text.setSelectedItem(model.getValueAt(Myindex,3)+"");
        Customer_address_text.setText(model.getValueAt(Myindex,4)+"");
        Customer_Balance_text.setText(model.getValueAt(Myindex,7)+"");
        Create_Button1.setVisible(false);
        Edit_Button2.setVisible(true);
        Customer_Name_text.setEnabled(false);
        Customer_password_text.setEnabled(false);
        Customer_Gender_text.setEnabled(false);
        Customer_birth_date_text.setEnabled(false);
        Customer_Balance_text.setEnabled(false);

        
        
        
     
    }//GEN-LAST:event_Customer_TableMouseClicked

    private void Edit_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_Button2ActionPerformed
       
        
        try {
            
            
            // name =  ' ahamed ' 
            
            int phoneno = Integer.parseInt(Customer_phone_no_text.getText());
            double Balance = Double.parseDouble(Customer_Balance_text.getText());
            String q = " update User1.Customer set email = '" + Customer_Email_text.getText() + "', address = '" + Customer_address_text.getText()+"' ,balance = " + Balance +" ,phonenumber = " + phoneno + " where  serialnumber  = " + Customer_serial_number;                                                           
            Statement Edit = con.createStatement();
            Edit.executeUpdate(q);
            JOptionPane.showMessageDialog(this, "Employee edit Successfully");
            show_customer_On_Table();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Home_Manager_Access.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("error in edit");
        }
        
        
        
    }//GEN-LAST:event_Edit_Button2ActionPerformed

    
/*
    
   int new_serial_number = 0;
   
   private void serial_number_count(){
        
        
        try {
            st2 = con.createStatement();
            rs2 = st2.executeQuery("select Max(serialnumber) form user1.customer");
            rs2.next();
            new_serial_number  = rs2.getInt(1)+1;
        } catch (SQLException ex) {
            Logger.getLogger(Home_Employee_Create_Account.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }*/
    int new_s_n = 0;
    private void S_N_count(){
        try {
            st2 = con.createStatement();
            String SQL = " select MAX (SERIALNUMBER) from User1.Customer ";
            rs2 = st2.executeQuery(SQL);
            rs2.next();
            new_s_n = (rs2.getInt(1) + 1 );
        } catch (SQLException ex) {
            Logger.getLogger(Home_Employee_Create_Account.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
   
   
   
    public void show_customer_On_Table() {
        try {
            st = con.createStatement();
            rs = st.executeQuery("SELECT serialnumber,name,birthdate,gender,address,phonenumber,email,Balance FROM customer ");
            Customer_Table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Employee_Create_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Employee_Create_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Employee_Create_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Employee_Create_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Employee_Create_Account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create_Button1;
    private javax.swing.JTextField Customer_Balance_text;
    private javax.swing.JTextField Customer_Email_text;
    private javax.swing.JComboBox<String> Customer_Gender_text;
    private javax.swing.JTextField Customer_Name_text;
    private javax.swing.JTable Customer_Table;
    private javax.swing.JTextField Customer_address_text;
    private javax.swing.JTextField Customer_birth_date_text;
    private javax.swing.JPasswordField Customer_password_text;
    private javax.swing.JTextField Customer_phone_no_text;
    private javax.swing.JButton Edit_Button2;
    private javax.swing.JLabel Employee_Email;
    private javax.swing.JButton Reset_Button2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
